[theme]
baseFontSize=18
font = "sans serif"
buttonRadius = "large"

[theme.light]
primaryColor = "#007A73"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#e3e3e3"
textColor = "#262730"

[theme.dark]
primaryColor = "#107C10"
backgroundColor = "#444"
borderColor = "#107C10"

[server]
fileWatcherType = "poll"
runOnSave = true
